#
# The rocket configuration file
#
# This is the place where you can configure the package archive URLs.
# Archives listed earlier in this file take precedence over archives
# listed later.
#
# The archive URL is the directory containing the *.gem files and
# the packages.db file.
#
# Only use archives with packages which are binary-compatible to the
# locally installed system!
#

# Add 'archive' entries with the URLs of the GEM archives you want to use.
###
# archive http://example.com/path/to/archive
# archive file:///local/dirs/are/also/possible

# A 'meta archive' is an URL of a text file containing the URL of a GEM
# archive.
###
# meta-archive http://example.com/path/to/meta/archive
# meta-archive file:///local/dirs/are/also/possible

# Add 'ignore' entries for the packages which should be ignored
# by rocket (install/update/search/...). It is also possible to
# use regular expressions here.
###
# ignore pkgname1 pkgname2 pkgname2
# ignore regular-expression

